% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\documentclass[
]{article}
\usepackage{xcolor}
\usepackage{titlesec}
\titlespacing*{\subsubsection}{0pt}{*0}{0pt}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={ProblemSet2},
  pdfauthor={Onno},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{ProblemSet2}
\author{Onno}
\date{2025-10-14}

\begin{document}
\maketitle

\subsection{1. Standard Preparation}\label{Preparation}%
Before starting, we clear the working evironment and set the working directory with this code
\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{rm}\NormalTok{(}\AttributeTok{list=}\FunctionTok{ls}\NormalTok{())}

\FunctionTok{setwd}\NormalTok{(}\StringTok{"C:/Users/onnos/Desktop/TRINITY/PhD/RStudio"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\subsection{2. Question 1}\label{question-1}
This section gives the code to answers to the part a-d of the first question in the Problem Set.

First, we need to import the data presented in the Problem Set into R. We'll do this manually using the code below: creating a matrix ("obs") that contains our values.

Second, we change the row- and column names to match the original data and make the data easier understandable. the line "obs" opens the table to see if it worked.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{obs }\OtherTok{\textless{}{-}} \FunctionTok{matrix}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\DecValTok{14}\NormalTok{, }\DecValTok{7}\NormalTok{,   }\CommentTok{\# Not Stopped}
                \DecValTok{6}\NormalTok{, }\DecValTok{7}\NormalTok{,    }\CommentTok{\# Bribe requested}
                \DecValTok{7}\NormalTok{, }\DecValTok{1}\NormalTok{),   }\CommentTok{\# Stopped/given warning}
              \AttributeTok{nrow =} \DecValTok{2}\NormalTok{,}
              \AttributeTok{byrow =} \ConstantTok{FALSE}\NormalTok{)}

\FunctionTok{rownames}\NormalTok{(obs) }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"Upper Class"}\NormalTok{, }\StringTok{"Lower Class"}\NormalTok{)}
\FunctionTok{colnames}\NormalTok{(obs) }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"NotStopped"}\NormalTok{, }\StringTok{"Bribe"}\NormalTok{, }\StringTok{"Stopped"}\NormalTok{)}
\NormalTok{obs}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##             NotStopped Bribe Stopped
## Upper Class         14     6       7
## Lower Class          7     7       1
\end{verbatim}

We can see that our original data is now imported into R. \newline


\subsubsection{2.1. Subtask 1}\label{Question-1-Subtask-1}
For our chi-square calculation we need to know some general info: our row and column sums, as well as the grand total of observations. 

After this, we can calculate our expected values under the assupmtion of statistical independency of our variables. Statistic indedendence in this case means that we assume that the distributions of the population is identical across categories.

We need the expected values for the chi-square calculation. The code saves them in the object "expected". The last line opens the new table with the expected distributions.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{row\_totals }\OtherTok{\textless{}{-}} \FunctionTok{rowSums}\NormalTok{(obs) }\DocumentationTok{\#\#27 and 15!}
\NormalTok{col\_totals }\OtherTok{\textless{}{-}} \FunctionTok{colSums}\NormalTok{(obs) }\DocumentationTok{\#\#21, 13 and 8}
\NormalTok{grand\_total }\OtherTok{\textless{}{-}} \FunctionTok{sum}\NormalTok{(obs) }\DocumentationTok{\#\#42}

\NormalTok{expected }\OtherTok{\textless{}{-}} \FunctionTok{outer}\NormalTok{(row\_totals, col\_totals) }\SpecialCharTok{/}\NormalTok{ grand\_total}
\NormalTok{expected}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##             NotStopped    Bribe  Stopped
## Upper Class       13.5 8.357143 5.142857
## Lower Class        7.5 4.642857 2.857143
\end{verbatim}

We can see that our calculations worked. The table above shows the expected values.

We can now calculate our chi-square using the standard formula:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{chi\_sq }\OtherTok{\textless{}{-}} \FunctionTok{sum}\NormalTok{((obs }\SpecialCharTok{{-}}\NormalTok{ expected)}\SpecialCharTok{\^{}}\DecValTok{2} \SpecialCharTok{/}\NormalTok{ expected)}
\NormalTok{chi\_sq}
\end{Highlighting}
\end{Shaded}
We can see, our chi-square value is 3.791168\newline
This is the test statistic that we are going to use for our hypothesis test(s).\newline


\subsubsection{2.2. Subtask 2}\label{Subtask-2-Question-1}
For this task, we need to first calculate our degrees of freedom using the standard fomula: df=(r−1)*(c−1). We have two rows and three columns in our data.

Using this we can then calculate our p-value. The code below does all this.  
\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df }\OtherTok{\textless{}{-}}\NormalTok{ (}\DecValTok{2{-}1}\NormalTok{)}\SpecialCharTok{*}\NormalTok{(}\DecValTok{3{-}1}\NormalTok{)}

\NormalTok{p\_value }\OtherTok{\textless{}{-}} \FunctionTok{pchisq}\NormalTok{(chi\_sq, df, }\AttributeTok{lower.tail =}\NormalTok{ F)}
\NormalTok{p\_value}
\end{Highlighting}
\end{Shaded}
\begin{verbatim}
## [1] 0.1502306
\end{verbatim}
We can see - our calculated p-value is 0.15\newline
At the 0.1 significance level, the p-value of 0.15 indicates that we do not reject the null hypothesis. There is no statistically significant evidence that the observed frequencies differ from the expected frequencies (or that the variables are dependent).\newline


\subsubsection{2.3. Subtask 3}\label{Subtask-3-Question-1}
We want to know our standardized residuals. Using the standard fomula, we run this code:
\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{std\_resid }\OtherTok{\textless{}{-}} \FunctionTok{as.data.frame}\NormalTok{((obs }\SpecialCharTok{{-}}\NormalTok{ expected) }\SpecialCharTok{/} \FunctionTok{sqrt}\NormalTok{(expected))}
\FunctionTok{print}\NormalTok{(std\_resid)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##             NotStopped      Bribe   Stopped
## Upper Class  0.1360828 -0.8153742  0.818923
## Lower Class -0.1825742  1.0939393 -1.098701
\end{verbatim}
We can see that the caluclation works, the standardized residuals are in the table above. 
In the table presented in the ProblemSet, it looks like this: 
\begin{table}[h]
	\centering
	\begin{tabular}{l | c c c }
		& Not Stopped & Bribe requested & Stopped/given warning \\
		\\[-1.8ex] 
		\hline \\[-1.8ex]
		Upper class  & 0.136 & -0.815 & 0.819 \\
		\\[-1.8ex]
		Lower class & -0.183 & 1.094 & -1.099 \\
	\end{tabular}
	\caption{Standardized residuals from the Chi-square test by class and outcome}
	\label{tab:chi2-residuals}
\end{table}

\subsubsection{2.4. Subtask 4}\label{subtask-4-question-1}
Standardized residuals in Chi-square tests provide a detailed, cell-level view of the results. While the overall Chi-square statistic indicates whether the observed frequencies deviate significantly from the expected ones, standardized residuals show which cells have observed values that are unusually higher or lower than expected. Positive residuals indicate that a value is above expectation, negative residuals indicate it is below, and the magnitude reflects the strength of the deviation. These residuals are important because they give a finer-grained picture of the patterns behind the single test statistic and can reveal interesting local deviations even when the overall test is not significant. They help identify which cells are driving the observed associations or differences in the data. 

Regarding our table from Subtask 3 we can now say: 
The cell-level standardized residuals show only minor deviations from expected counts, with all residuals less than 2 in magnitude. This indicates that none of the individual cells differ notably from expectation, consistent with the overall Chi-square test result of p = 0.15, and suggests no strong association between social class and the stopping outcome.\newline


\subsection{3. Question 2}\label{question-2}
To start, we need to load the data into our environment. To do so, we save the URL of the data as an object and then read it from that url into the environment.
\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{url }\OtherTok{\textless{}{-}} \StringTok{"https://raw.githubusercontent.com/kosukeimai/qss/master/PREDICTION/women.csv"}
\NormalTok{df }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(url, }\AttributeTok{header =} \ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\subsubsection{3.1. Subtask 1}\label{subtask-1}

H0: There is no difference in the number of new (or repaired) water sources between villages that are lead by men and villages that are lead by women

H1: The number of new (or repaired) water sources in villages that are lead by men is higher (or lower!) than in villages that are lead by women


\subsubsection{3.2. Subtask 2}\label{subtask-2}
To run the regression, we first need to fit our model. The code below specifies the model. We take the variable "female" not "reserved" because we want the effect of women-led villages, not only the effect in the villages that were reserved for women.
\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{regression }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(water }\SpecialCharTok{\textasciitilde{}}\NormalTok{ female, }\AttributeTok{data =}\NormalTok{ df)}
\end{Highlighting}
\end{Shaded}

\subsubsection{3.3. Subtask 3}\label{subtask-3}
First, let's see the results of the regression.
\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(regression)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = water ~ female, data = df)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -22.68 -14.78  -7.81   2.29 317.32 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept)   14.813      2.382   6.220 1.56e-09 ***
## female         7.864      3.838   2.049   0.0413 *  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 33.51 on 320 degrees of freedom
## Multiple R-squared:  0.01295,    Adjusted R-squared:  0.009867 
## F-statistic: 4.199 on 1 and 320 DF,  p-value: 0.04126
\end{verbatim}


The regression results indicate that female leadership has a positive effect on the number of new or repaired drinking water facilities. Villages governed by female council heads are predicted to have, on average, about 7.86 more facilities than those governed by men. This effect is statistically significant at the 5\% level (p = 0.041), allowing us to reject the null hypothesis that female leadership has no impact. However, the model explains only a small portion of the variation in water facilities (R Squared = 0.013), suggesting that other factors also play an important role.



However, I am confused about the phrasing "reservation policy" in the question, so let's check the effect of "reserved" as well in a second regression model. 

\begin{Shaded}
	\begin{Highlighting}[]
\NormalTok{regression2 }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(water }\SpecialCharTok{\textasciitilde{}}\NormalTok{ reserved, }\AttributeTok{data =}\NormalTok{ df)}
\FunctionTok{summary}\NormalTok{(regression2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = water ~ reserved, data = df)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -23.991 -14.738  -7.865   2.262 316.009 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept)   14.738      2.286   6.446 4.22e-10 ***
## reserved       9.252      3.948   2.344   0.0197 *  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 33.45 on 320 degrees of freedom
## Multiple R-squared:  0.01688,    Adjusted R-squared:  0.0138 
## F-statistic: 5.493 on 1 and 320 DF,  p-value: 0.0197
\end{verbatim}

We also reject the null hypothesis at the 5\% level. The effect is even larger in this case: villages that were reserved for female council heads have, on average, 9.25 more new or repaired drinking water facilities than villages governed by men.

\end{document}
